services:
  - type: web
    name: campusquest
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: NODE_ENV
        value: production

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: 3306

      - key: DB_USER
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: DB_NAME
        sync: false

      - key: SESSION_SECRET
        generateValue: true

    healthCheckPath: /

    autoDeploy: true
